version: '3'
services:
  graphql:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/app:cached
    command: air -c .art.toml
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
